export type Company = {
  name: string;
  desc: string;
  sector: string;
  status: "active" | "exited";
};

export const portfolio: Company[] = [
  { name: "n26", desc: "the next generation mobile bank", sector: "fintech", status: "active" },
  { name: "taxfix", desc: "mobile first tax assistant", sector: "fintech", status: "active" },
  { name: "klarna", desc: "the flexible payment provider", sector: "fintech", status: "active" },
  { name: "inkitt", desc: "the reader-powered book publisher", sector: "consumer", status: "active" },
  { name: "carvolution", desc: "the next generation car subscription service", sector: "consumer platforms", status: "active" },
  { name: "mistral ai", desc: "fast, open-source, and secure language models", sector: "ai/ml", status: "active" },
  { name: "9fin", desc: "smarter, faster leveraged finance intelligence", sector: "fintech", status: "active" },
  { name: "vivenu", desc: "full service ticketing solution", sector: "saas", status: "active" },
  { name: "hypervision surgical", desc: "making surgeries more precise, safer, and faster", sector: "healthtech", status: "active" },
  { name: "proxima fusion", desc: "a truly stellar source of energy", sector: "energy", status: "active" },
  { name: "hilo", desc: "continuous blood pressure monitoring solution", sector: "healthtech", status: "active" },
  { name: "lakera", desc: "supporting ai teams to build safe, trustworthy products", sector: "ai/ml", status: "exited" },
  { name: "dunia", desc: "accelerating chemical industry decarbonization", sector: "climatetech", status: "active" },
  { name: "flexion", desc: "giving robots a brain", sector: "robotics", status: "active" },
  { name: "swap food", desc: "plant-based whole cut meat and fish", sector: "foodtech", status: "active" },
  { name: "knowunity", desc: "leading social learning platform", sector: "edtech", status: "active" },
  { name: "apoha", desc: "a new kind of machine intelligence", sector: "frontier science & biotech", status: "active" },
  { name: "zenjob", desc: "full service on-demand staffing platform", sector: "marketplace", status: "active" },
  { name: "lyceum", desc: "reimagining access to compute in the AI era", sector: "saas", status: "active" },
  { name: "basecamp research", desc: "revolutionizing genome design", sector: "biotech", status: "active" },
  { name: "synthesized", desc: "accelerating enterprise software in the ai era", sector: "ai/ml", status: "active" },
  { name: "infinite roots", desc: "creating the food of the future from fungi", sector: "foodtech", status: "active" },
  { name: "legalfly", desc: "the premier ai copilot for legal teams", sector: "ai/ml", status: "active" },
  { name: "biolux", desc: "advanced light-accelerated orthodontics", sector: "healthtech", status: "active" },
  { name: "relai", desc: "easy bitcoin investing", sector: "fintech", status: "active" },
  { name: "dejablue", desc: "powering flexible energy for the ev era", sector: "climatetech", status: "active" },
  { name: "razor", desc: "next generation global consumer conglomerate", sector: "ecommerce", status: "active" },
  { name: "uncommon", desc: "a sustainable and cruelty-free approach to meat production", sector: "foodtech", status: "active" },
  { name: "forgis", desc: "enhancing industrial automation with ai", sector: "robotics", status: "active" },
  { name: "011h", desc: "accelerating the world's transition to sustainable building development", sector: "energy & climate tech", status: "active" },
  { name: "expressionedits", desc: "getting genetic syntax right", sector: "biotech", status: "active" },
  { name: "apaleo", desc: "open hospitality cloud", sector: "vertical ai & enterprise software", status: "active" },
  { name: "magdrive", desc: "next-generation spacecraft propulsion", sector: "spacetech", status: "active" },
  { name: "better dairy", desc: "animal-free dairy production", sector: "foodtech", status: "active" },
  { name: "level zero health", desc: "pioneering the future of hormone monitoring", sector: "biotech", status: "active" },
  { name: "albatross", desc: "next-gen ai-driven personalization", sector: "vertical ai & enterprise software", status: "active" },
  { name: "daltontx", desc: "powering the intelligence backbone of drug discovery", sector: "healthtech", status: "active" },
  { name: "memo therapeutics", desc: "mining the human antibody repertoire to discover new therapies", sector: "biotech", status: "active" },
  { name: "valink", desc: "unlocking the next frontier of cancer therapy", sector: "healthtech", status: "active" },
  { name: "sennder", desc: "digital freight forwarder", sector: "marketplace", status: "active" },
  { name: "helical ai", desc: "bio foundation models at the fingertips of scientists", sector: "frontier science & biotech", status: "active" },
  { name: "immunos", desc: "the next generation of novel immunotherapies", sector: "biotech", status: "active" },
  { name: "voize", desc: "voice assistant for care workers", sector: "healthtech", status: "active" },
  { name: "sanity group", desc: "unlocking the benefits of cannabinoids", sector: "healthtech", status: "active" },
  { name: "kenjo", desc: "hr & culture platform for engaged employees", sector: "saas", status: "active" },
  { name: "showheroes", desc: "mobile video solutions for publishers and advertisers", sector: "adtech", status: "active" },
  { name: "natif ai", desc: "next-level document processing automation", sector: "ai/ml", status: "active" },
  { name: "morressier", desc: "organizing the world's early scientific findings", sector: "vertical ai & enterprise software", status: "active" },
  { name: "neutral", desc: "next generation exchange for environmental assets", sector: "climatetech", status: "active" },
  { name: "bnext", desc: "mobile-first financial hub", sector: "fintech", status: "active" },
  { name: "pave", desc: "data-driven credit building platform", sector: "fintech", status: "active" },
  { name: "jodel", desc: "location based social network", sector: "consumer", status: "active" },
  { name: "whaly", desc: "data processing made easy", sector: "saas", status: "active" },
  { name: "buena", desc: "the next generation of digital smart tools for property management", sector: "vertical ai & enterprise software", status: "active" },
  { name: "beams", desc: "ai insights platform for highly regulated industries", sector: "ai/ml", status: "exited" },
  { name: "robinhood", desc: "democratizing finance for all", sector: "fintech", status: "exited" },
  { name: "teads", desc: "the global media platform", sector: "adtech", status: "exited" },
  { name: "enway", desc: "technology for autonomous special-purpose vehicles", sector: "robotics", status: "exited" },
  { name: "lunaphore", desc: "spatial biotech platform for immuno-oncology research", sector: "biotech", status: "exited" },
  { name: "bexio", desc: "business and accounting platform for smes", sector: "saas", status: "exited" },
  { name: "araris", desc: "high-performance adc linker technology for targeted cancer therapy", sector: "frontier science & biotech", status: "exited" },
];

export const sectors = [...new Set(portfolio.map((c) => c.sector))].sort();
